export const POST_GET_ALL = "POST_GET_ALL";
export const POST_GET_ALL_SUCCESS = "POST_GET_ALL_SUCCESS";
export const POST_GET_ALL_ERROR = "POST_GET_ALL_ERROR";

// per category
export const POST_GET_ALL_PER_CATEGORY = "POST_GET_ALL_PER_CATEGORY";
export const POST_GET_ALL_PER_CATEGORY_SUCCESS = "POST_GET_ALL_PER_CATEGORY_SUCCESS";
export const POST_GET_ALL_PER_CATEGORY_ERROR = "POST_GET_ALL_PER_CATEGORY_ERROR";