"use strict";
exports.__esModule = true;
var http = require("http");
var app_1 = require("./app");
var dotenv = require("dotenv");
var Utils_1 = require("./class/Utils");
dotenv.config();
var utils = new Utils_1["default"];
var server = http.createServer(app_1["default"]);
var port = utils.normalizePort(process.env.PORT || 3000);
server.on("listening", function () { return utils.logHandler(port, server); });
server.listen(port);
